import Africa from './regions/africa';
import Asia from './regions/asia';
import Europe from './regions/europe';
import MiddleEast from './regions/middle_east';
import NorthAmerica from './regions/north_america';
import Oceania from './regions/oceania';
import SouthAmerica from './regions/south_america';
import AfricaRegionals from './regions/africa/africa';
import AsiaRegionals from './regions/asia/asia';
import EuropeRegionals from './regions/europe/europe';
import MiddleEastRegionals from './regions/middle_east/middle_east';
import NorthAmericaRegionals from './regions/north_america/north_america';
import OceaniaRegionals from './regions/oceania/oceania';
import SouthAmericaRegionals from './regions/south_america/south_america';

/** @internal */
const ALL_REGIONS = [
  ...AfricaRegionals.AFRICA_LANGUAGES,
  ...AsiaRegionals.ASIA_LANGUAGES,
  ...EuropeRegionals.EUROPE_LANGUAGES,
  ...MiddleEastRegionals.MIDDLE_EAST_LANGUAGES,
  ...NorthAmericaRegionals.NORTH_AMERICA_LANGUAGES,
  ...OceaniaRegionals.OCEANIA_LANGUAGES,
  ...SouthAmericaRegionals.SOUTH_AMERICA_LANGUAGES,
].sort();

const REGIONALS_LANGUAGES = ALL_REGIONS as ReadonlyArray<(typeof ALL_REGIONS)[number]>;

type RegionalLanguage = (typeof REGIONALS_LANGUAGES)[number];

export type { RegionalLanguage };

export type {
  AfricaAfrikaansLanguage,
  AfricaAkanLanguage,
  AfricaAmharicLanguage,
  AfricaArabicLanguage,
  AfricaBambaraLanguage,
  AfricaBembaLanguage,
  AfricaDholuoLanguage,
  AfricaEweLanguage,
  AfricaFulaniLanguage,
  AfricaGaLanguage,
  AfricaHausaLanguage,
  AfricaIgboLanguage,
  AfricaKabyleLanguage,
  AfricaKambaLanguage,
  AfricaKanuriLanguage,
  AfricaKikuyuLanguage,
  AfricaKinyarwandaLanguage,
  AfricaKirundiLanguage,
  AfricaLingalaLanguage,
  AfricaLubaKasaiLanguage,
  AfricaLugandaLanguage,
  AfricaLuoLanguage,
  AfricaMalagasyLanguage,
  AfricaMeruLanguage,
  AfricaMossiLanguage,
  AfricaNyanjaLanguage,
  AfricaOromoLanguage,
  AfricaPortugueseLanguage,
  AfricaSangoLanguage,
  AfricaSesothoLanguage,
  AfricaShonaLanguage,
  AfricaSomaliLanguage,
  AfricaSoninkeLanguage,
  AfricaSwahiliLanguage,
  AfricaSwatiLanguage,
  AfricaTigrinyaLanguage,
  AfricaTsongaLanguage,
  AfricaTswanaLanguage,
  AfricaTumbukaLanguage,
  AfricaTwiLanguage,
  AfricaVendaLanguage,
  AfricaWolofLanguage,
  AfricaXhosaLanguage,
  AfricaYorubaLanguage,
  AfricaZuluLanguage,
  AfricaLanguage,
} from './regions/africa/africa';

export type {
  AsiaAcehneseLanguage,
  AsiaAssameseLanguage,
  AsiaAwadhiLanguage,
  AsiaBalineseLanguage,
  AsiaBanjarLanguage,
  AsiaBashkirLanguage,
  AsiaBatakLanguage,
  AsiaBengaliLanguage,
  AsiaBhojpuriLanguage,
  AsiaBikolLanguage,
  AsiaBugineseLanguage,
  AsiaBurmeseLanguage,
  AsiaCantoneseLanguage,
  AsiaCebuanoLanguage,
  AsiaChhattisgarhiLanguage,
  AsiaChineseLanguage,
  AsiaChittagonianLanguage,
  AsiaChuvashLanguage,
  AsiaDzongkhaLanguage,
  AsiaFilipinoLanguage,
  AsiaGanLanguage,
  AsiaGarhwaliLanguage,
  AsiaGondiLanguage,
  AsiaGujaratiLanguage,
  AsiaHakkaLanguage,
  AsiaHaryanviLanguage,
  AsiaHiligaynonLanguage,
  AsiaHindiLanguage,
  AsiaHmongLanguage,
  AsiaIlocanoLanguage,
  AsiaIndonesianLanguage,
  AsiaJapaneseLanguage,
  AsiaJavaneseLanguage,
  AsiaKannadaLanguage,
  AsiaKapampanganLanguage,
  AsiaKarenLanguage,
  AsiaKashmiriLanguage,
  AsiaKazakhLanguage,
  AsiaKhmerLanguage,
  AsiaKomiLanguage,
  AsiaKonkaniLanguage,
  AsiaKoreanLanguage,
  AsiaKyrgyzLanguage,
  AsiaLaoLanguage,
  AsiaMadureseLanguage,
  AsiaMaithiliLanguage,
  AsiaMakassarLanguage,
  AsiaMalayLanguage,
  AsiaMalayalamLanguage,
  AsiaMandarinLanguage,
  AsiaManipuriLanguage,
  AsiaMaranaoLanguage,
  AsiaMarathiLanguage,
  AsiaMarwariLanguage,
  AsiaMeiteiLanguage,
  AsiaMinNanLanguage,
  AsiaMinangkabauLanguage,
  AsiaMonLanguage,
  AsiaMongolianLanguage,
  AsiaNepaliLanguage,
  AsiaNewarLanguage,
  AsiaOdiaLanguage,
  AsiaPangasinanLanguage,
  AsiaPunjabiLanguage,
  AsiaRajasthaniLanguage,
  AsiaRohingyaLanguage,
  AsiaSanskritLanguage,
  AsiaSantaliLanguage,
  AsiaShanLanguage,
  AsiaSindhiLanguage,
  AsiaSinhalaLanguage,
  AsiaSundaneseLanguage,
  AsiaSylhetiLanguage,
  AsiaTagalogLanguage,
  AsiaTajikLanguage,
  AsiaTamilLanguage,
  AsiaTatarLanguage,
  AsiaTeluguLanguage,
  AsiaTetumLanguage,
  AsiaThaiLanguage,
  AsiaTibetanLanguage,
  AsiaTurkmenLanguage,
  AsiaUdmurtLanguage,
  AsiaUrduLanguage,
  AsiaUyghurLanguage,
  AsiaUzbekLanguage,
  AsiaVietnameseLanguage,
  AsiaWarayLanguage,
  AsiaWuLanguage,
  AsiaXiangLanguage,
  AsiaYakutLanguage,
  AsiaLanguage,
} from './regions/asia/asia';

export type {
  EuropeAlbanianLanguage,
  EuropeArmenianLanguage,
  EuropeAzerbaijaniLanguage,
  EuropeBasqueLanguage,
  EuropeBelarusianLanguage,
  EuropeBosnianLanguage,
  EuropeBretonLanguage,
  EuropeBulgarianLanguage,
  EuropeCatalanLanguage,
  EuropeCorsicanLanguage,
  EuropeCroatianLanguage,
  EuropeCzechLanguage,
  EuropeDanishLanguage,
  EuropeDutchLanguage,
  EuropeEnglishLanguage,
  EuropeEsperantoLanguage,
  EuropeEstonianLanguage,
  EuropeFaroeseLanguage,
  EuropeFinnishLanguage,
  EuropeFrenchLanguage,
  EuropeFrisianLanguage,
  EuropeGalicianLanguage,
  EuropeGeorgianLanguage,
  EuropeGermanLanguage,
  EuropeGreekLanguage,
  EuropeHungarianLanguage,
  EuropeIcelandicLanguage,
  EuropeIrishLanguage,
  EuropeItalianLanguage,
  EuropeKashubianLanguage,
  EuropeLatinLanguage,
  EuropeLatvianLanguage,
  EuropeLigurianLanguage,
  EuropeLimburgishLanguage,
  EuropeLithuanianLanguage,
  EuropeLombardLanguage,
  EuropeLuxembourgishLanguage,
  EuropeMacedonianLanguage,
  EuropeMalteseLanguage,
  EuropeMirandeseLanguage,
  EuropeMontenegrinLanguage,
  EuropeNorwegianLanguage,
  EuropeOccitanLanguage,
  EuropePolishLanguage,
  EuropePortugueseLanguage,
  EuropeRomaniLanguage,
  EuropeRomanianLanguage,
  EuropeRomanshLanguage,
  EuropeRussianLanguage,
  EuropeSardinianLanguage,
  EuropeScotsLanguage,
  EuropeSerbianLanguage,
  EuropeSicilianLanguage,
  EuropeSilesianLanguage,
  EuropeSlovakLanguage,
  EuropeSlovenianLanguage,
  EuropeSpanishLanguage,
  EuropeSwedishLanguage,
  EuropeUkrainianLanguage,
  EuropeVenetianLanguage,
  EuropeWelshLanguage,
  EuropeYiddishLanguage,
  EuropeLanguage,
} from './regions/europe/europe';

export type {
  MiddleeastArabicLanguage,
  MiddleeastDariLanguage,
  MiddleeastHebrewLanguage,
  MiddleeastKurdishLanguage,
  MiddleeastPashtoLanguage,
  MiddleeastPersianLanguage,
  MiddleeastTurkishLanguage,
  MiddleeastLanguage,
} from './regions/middle_east/middle_east';

export type {
  NorthamericaCreeLanguage,
  NorthamericaEnglishLanguage,
  NorthamericaFrenchLanguage,
  NorthamericaHaitianCreoleLanguage,
  NorthamericaHawaiianLanguage,
  NorthamericaInuktitutLanguage,
  NorthamericaMayaLanguage,
  NorthamericaMixtecLanguage,
  NorthamericaNahuatlLanguage,
  NorthamericaNavajoLanguage,
  NorthamericaOjibweLanguage,
  NorthamericaSpanishLanguage,
  NorthamericaYucatecMayaLanguage,
  NorthamericaZapotecLanguage,
  NorthamericaLanguage,
} from './regions/north_america/north_america';

export type {
  OceanianEnglishLanguage,
  OceanianFijianLanguage,
  OceanianMaoriLanguage,
  OceanianSamoanLanguage,
  OceanianTahitianLanguage,
  OceanianTonganLanguage,
  OceanianTuvaluLanguage,
  OceanianLanguage,
} from './regions/oceania/oceania';

export type {
  SouthamericaAymaraLanguage,
  SouthamericaGuaraniLanguage,
  SouthamericaMapudungunLanguage,
  SouthamericaPortugueseLanguage,
  SouthamericaQuechuaLanguage,
  SouthamericaSpanishLanguage,
  SouthamericaLanguage,
} from './regions/south_america/south_america';

export default {
  ...Africa,
  ...Asia,
  ...Europe,
  ...MiddleEast,
  ...NorthAmerica,
  ...Oceania,
  ...SouthAmerica,
  AfricaRegionals,
  AsiaRegionals,
  EuropeRegionals,
  MiddleEastRegionals,
  NorthAmericaRegionals,
  OceaniaRegionals,
  SouthAmericaRegionals,
  REGIONALS_LANGUAGES,
};
